#!/bin/bash
# subdomains listing and resolving IPs from the index.html file already downloaded from www.megacorpone.com

# removing files generated by a previous run of this script
rm subdomains_list.txt subdomains_IPs_list.txt

# catching all subdomains name of megacorpone.com except www.megacorpone.com and cuting to keep only the domains names. Saving to a file
cat index.html | grep megacorpone.com | grep -v "www\.megacorpone\.com" | cut -d "/" -f 3 | awk -F '"' '{print $1}' | sort -u > subdomains_list.txt

# for any subdomain in the file, resolve IP and keep only IPv4 address in x.x.x.x format
for subdomain in $(cat subdomains_list.txt)
do
    host $subdomain | cut -d " " -f 4 | sort -u >> subdomains_IPs_list.txt
done
